-- Insert Vietnamese TikTok Influencers
-- vietnam_influencers 테이블에 인플루언서 데이터 삽입

INSERT INTO vietnam_influencers (name, city, niches, languages, platforms, display_order)
VALUES
  ('nanavivuvu', NULL, ARRAY['Fashion', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nanavivuvu", "followers": 0, "url": "https://www.tiktok.com/@nanavivuvu"}]'::jsonb, 1),
  ('Tamii 따미', NULL, ARRAY['Vlog', 'Place review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "tamtrann251", "followers": 0, "url": "https://www.tiktok.com/@tamtrann251"}]'::jsonb, 2),
  ('gjiang.g', NULL, ARRAY['Vlog', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "gjiang.g", "followers": 0, "url": "https://www.tiktok.com/@gjiang.g"}]'::jsonb, 3),
  ('Dolri.nn', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dolri.nn", "followers": 0, "url": "https://www.tiktok.com/@dolri.nn"}]'::jsonb, 4),
  ('dtthao.anh', NULL, ARRAY['Vlog', 'Review', 'Fashion'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dtthao.anh", "followers": 0, "url": "https://www.tiktok.com/@dtthao.anh"}]'::jsonb, 5),
  ('giadinhgauto', NULL, ARRAY['Vlog', 'Food review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "giadinhgauto", "followers": 0, "url": "https://www.tiktok.com/@giadinhgauto"}]'::jsonb, 6),
  ('Phanh Daily', NULL, ARRAY['Livestream', 'Model', 'Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "ph.anhhvu", "followers": 0, "url": "https://www.tiktok.com/@ph.anhhvu"}]'::jsonb, 7),
  ('Phí Nguyễn Thùy Linh', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mcphilinh", "followers": 0, "url": "https://www.tiktok.com/@mcphilinh"}]'::jsonb, 8),
  ('Hoàng Duyên', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hoangduyen0406", "followers": 0, "url": "https://www.tiktok.com/@hoangduyen0406"}]'::jsonb, 9),
  ('Tú Anh Đặng', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "tutho0112", "followers": 0, "url": "https://www.tiktok.com/@tutho0112"}]'::jsonb, 10),
  ('Na Đây', NULL, ARRAY['Vlog', 'Review', 'Unbox'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "naday19_", "followers": 0, "url": "https://www.tiktok.com/@naday19_"}]'::jsonb, 11),
  ('Bachu', NULL, ARRAY['Vlog', 'Cooking'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "debaochau", "followers": 0, "url": "https://www.tiktok.com/@debaochau"}]'::jsonb, 12),
  ('Bạch Hà Nhã Chi', NULL, ARRAY['Beauty', 'Lifestyle', 'Fashion'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "berberbyday", "followers": 0, "url": "https://www.tiktok.com/@berberbyday"}]'::jsonb, 13),
  ('haiyen666', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "haiyen666", "followers": 0, "url": "https://www.tiktok.com/@haiyen666"}]'::jsonb, 14),
  ('Coding with Nina', NULL, ARRAY['Vlog', 'Office life'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "codingwithnina", "followers": 0, "url": "https://www.tiktok.com/@codingwithnina"}]'::jsonb, 15),
  ('Lynkam Daily', NULL, ARRAY['Vlog', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "camcammdaily", "followers": 0, "url": "https://www.tiktok.com/@camcammdaily"}]'::jsonb, 16),
  ('Minh Phương', NULL, ARRAY['Vlog', 'Travel', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mphuong.278", "followers": 0, "url": "https://www.tiktok.com/@mphuong.278"}]'::jsonb, 17),
  ('Yunedaybyday', NULL, ARRAY['Vlog', 'Fashion', 'Cooking'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "yuneedaybyday", "followers": 0, "url": "https://www.tiktok.com/@yuneedaybyday"}]'::jsonb, 18),
  ('Gia đình Miu Miu', NULL, ARRAY['Review', 'Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hanhvu996", "followers": 0, "url": "https://www.tiktok.com/@hanhvu996"}]'::jsonb, 19),
  ('Lamngocphuong', NULL, ARRAY['Vlog', 'Travel', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "lamphuongggg1104", "followers": 0, "url": "https://www.tiktok.com/@lamphuongggg1104"}]'::jsonb, 20),
  ('Thảo Anh lanh chanh', NULL, ARRAY['Lifestyle', 'Review', 'Travel', 'Beauty', 'F&B'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hoangthuthaoooo", "followers": 0, "url": "https://www.tiktok.com/@hoangthuthaoooo"}]'::jsonb, 21),
  ('onepurring.day', NULL, ARRAY['Vlog', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "onepurring.day", "followers": 0, "url": "https://www.tiktok.com/@onepurring.day"}]'::jsonb, 22),
  ('Tâm Xíu', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "tamxiu", "followers": 0, "url": "https://www.tiktok.com/@tamxiu"}]'::jsonb, 23),
  ('SunHT', NULL, ARRAY['Lifestyle', 'Model', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "sunht2309", "followers": 0, "url": "https://www.tiktok.com/@sunht2309"}]'::jsonb, 24),
  ('Trang Chuối', NULL, ARRAY['Livestream', 'Review', 'Cosmetics', 'Skincare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "trangchuoi.01", "followers": 0, "url": "https://www.tiktok.com/@trangchuoi.01"}]'::jsonb, 25),
  ('Thuận T Nguyễn', NULL, ARRAY['Vlog', 'Personal experiences'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "thuandaily", "followers": 0, "url": "https://www.tiktok.com/@thuandaily"}]'::jsonb, 26),
  ('Huyền Misu Mỹ Phẩm', NULL, ARRAY['Review', 'Lifestyle', 'Personal experiences'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "huyenmisu2024", "followers": 0, "url": "https://www.tiktok.com/@huyenmisu2024"}]'::jsonb, 27),
  ('Huyền Thu Boutique', NULL, ARRAY['Review', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dothuhuyen258", "followers": 0, "url": "https://www.tiktok.com/@dothuhuyen258"}]'::jsonb, 28),
  ('Thùy Dung', NULL, ARRAY['Review', 'Lifestyle', 'Personal experiences'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hantudu2110", "followers": 0, "url": "https://www.tiktok.com/@hantudu2110"}]'::jsonb, 29),
  ('good morning, teddie 🐻', NULL, ARRAY['Review', 'Home Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "babi_teddie", "followers": 0, "url": "https://www.tiktok.com/@babi_teddie"}]'::jsonb, 30),
  ('Uni nè', NULL, ARRAY['Vlog', 'Health', 'Fashion'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "lifebyuni", "followers": 0, "url": "https://www.tiktok.com/@lifebyuni"}]'::jsonb, 31),
  ('Tracy Nguyen', NULL, ARRAY['Lifestyle', 'F&B'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "tracy.tracy0212", "followers": 0, "url": "https://www.tiktok.com/@tracy.tracy0212"}]'::jsonb, 32),
  ('Phương Hà', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "phuongha96_", "followers": 0, "url": "https://www.tiktok.com/@phuongha96_"}]'::jsonb, 33),
  ('Happi Mommi', NULL, ARRAY['Family', 'Vlog', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "happi.mommi", "followers": 0, "url": "https://www.tiktok.com/@happi.mommi"}]'::jsonb, 34),
  ('Linh Rùaa', NULL, ARRAY['Review', 'Fashion', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "abt.ruaf", "followers": 0, "url": "https://www.tiktok.com/@abt.ruaf"}]'::jsonb, 35),
  ('Hà My Pinky', NULL, ARRAY['Review', 'Skincare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hamypinky2002", "followers": 0, "url": "https://www.tiktok.com/@hamypinky2002"}]'::jsonb, 36),
  ('HÀ LÊ', NULL, ARRAY['Lifestyle', 'Review', 'Skincare', 'Couple'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "itshale98", "followers": 0, "url": "https://www.tiktok.com/@itshale98"}]'::jsonb, 37),
  ('Mai Hà Trang', NULL, ARRAY['Lifestyle', 'Beauty', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mh_trang", "followers": 0, "url": "https://www.tiktok.com/@mh_trang"}]'::jsonb, 38),
  ('linhxinhquanxau', NULL, ARRAY['Lifestyle', 'Couple', 'Travel', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "linhxinhquanxau", "followers": 0, "url": "https://www.tiktok.com/@linhxinhquanxau"}]'::jsonb, 39),
  ('💎Liên Beauty💎', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mailienreview", "followers": 0, "url": "https://www.tiktok.com/@mailienreview"}]'::jsonb, 40),
  ('Quin', NULL, ARRAY['Family', 'Lifestyle', 'Skincare'], ARRAY['Vietnamese'], '[]'::jsonb, 41),
  ('_haeng04', NULL, ARRAY['Vlog', 'Study Tips', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "_haeng04", "followers": 0, "url": "https://www.tiktok.com/@_haeng04"}]'::jsonb, 42),
  ('Hanni Thúy Hiền', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hanniethuyhien", "followers": 0, "url": "https://www.tiktok.com/@hanniethuyhien"}]'::jsonb, 43),
  ('Mai Vân Trang', NULL, ARRAY['Lifestyle', 'Fashion', 'Review', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "maivantrang_", "followers": 0, "url": "https://www.tiktok.com/@maivantrang_"}]'::jsonb, 44),
  ('Khánh Li Vương', NULL, ARRAY['Lifestyle', 'Review', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "khnhlyvuong", "followers": 0, "url": "https://www.tiktok.com/@khnhlyvuong"}]'::jsonb, 45),
  ('Nhà Gấu Con', NULL, ARRAY['Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "thuyvo2711", "followers": 0, "url": "https://www.tiktok.com/@thuyvo2711"}]'::jsonb, 46),
  ('Bobby Tang', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "bobby.tang", "followers": 0, "url": "https://www.tiktok.com/@bobby.tang"}]'::jsonb, 47),
  ('Min', NULL, ARRAY['Review', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mincoconutt", "followers": 0, "url": "https://www.tiktok.com/@mincoconutt"}]'::jsonb, 48),
  ('Hiệp nè', NULL, ARRAY['Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "linknhii", "followers": 0, "url": "https://www.tiktok.com/@linknhii"}]'::jsonb, 49),
  ('Cô Hà ở Hà Nội', NULL, ARRAY['Lifestyle', 'Business', 'Makeup'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "cohaohanoi", "followers": 0, "url": "https://www.tiktok.com/@cohaohanoi"}]'::jsonb, 50),
  ('Gabon2699', NULL, ARRAY['Lifestyle', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "sopagetti", "followers": 0, "url": "https://www.tiktok.com/@sopagetti"}]'::jsonb, 51),
  ('Khánh D Linh', NULL, ARRAY['Lifestyle', 'Beauty', 'Review', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "khanh.d.linh", "followers": 0, "url": "https://www.tiktok.com/@khanh.d.linh"}]'::jsonb, 52),
  ('Quỳnh rì viu', NULL, ARRAY['Review', 'Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "quynhriviu_", "followers": 0, "url": "https://www.tiktok.com/@quynhriviu_"}]'::jsonb, 53),
  ('Bảo Yến Review', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "baoyenn88", "followers": 0, "url": "https://www.tiktok.com/@baoyenn88"}]'::jsonb, 54),
  ('Nguyễn Văn To', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "wan.to2k4", "followers": 0, "url": "https://www.tiktok.com/@wan.to2k4"}]'::jsonb, 55),
  ('rannhoreview', NULL, ARRAY['Fashion'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "rannhoreview", "followers": 0, "url": "https://www.tiktok.com/@rannhoreview"}]'::jsonb, 56),
  ('Chu cao', NULL, ARRAY['Review', 'Share tips', 'Skincare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "chucaoreview", "followers": 0, "url": "https://www.tiktok.com/@chucaoreview"}]'::jsonb, 57),
  ('luukimthanh.569', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "luukimthanh.569", "followers": 0, "url": "https://www.tiktok.com/@luukimthanh.569"}]'::jsonb, 58),
  ('Shin Leo''s Family', NULL, ARRAY['Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "meembeshin", "followers": 0, "url": "https://www.tiktok.com/@meembeshin"}]'::jsonb, 59),
  ('Nguyễn Tiến Anh', NULL, ARRAY['Review', 'Travel', 'F&B'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "ntanh_1612", "followers": 0, "url": "https://www.tiktok.com/@ntanh_1612"}]'::jsonb, 60),
  ('Yến tình', NULL, ARRAY['Lifestyle', 'Review', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "tinh_phat0701", "followers": 0, "url": "https://www.tiktok.com/@tinh_phat0701"}]'::jsonb, 61),
  ('XiuLing', NULL, ARRAY['Skincare', 'Cosmetics', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "xiuling4226", "followers": 0, "url": "https://www.tiktok.com/@xiuling4226"}]'::jsonb, 62),
  ('Đan tâm', NULL, ARRAY['Review', 'Share tips', 'Travel', 'F&B'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dan_tam0701", "followers": 0, "url": "https://www.tiktok.com/@dan_tam0701"}]'::jsonb, 63),
  ('Mai Linh', NULL, ARRAY['Lifestyle', 'Review', 'Cosmetics'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mlingggg", "followers": 0, "url": "https://www.tiktok.com/@mlingggg"}]'::jsonb, 64),
  ('Mẹ Zangkor Iu Đời', NULL, ARRAY['Review', 'Family', 'Lifestyle', 'Momcare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "zangkorean", "followers": 0, "url": "https://www.tiktok.com/@zangkorean"}]'::jsonb, 65),
  ('Ngọc Thiệp', NULL, ARRAY['Livestream', 'Lifestyle', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "ngocthiepp", "followers": 0, "url": "https://www.tiktok.com/@ngocthiepp"}]'::jsonb, 66),
  ('Liuuuliuu', NULL, ARRAY['Lifestyle', 'Couple', 'Skincare Review', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "liuuuliuu", "followers": 0, "url": "https://www.tiktok.com/@liuuuliuu"}]'::jsonb, 67),
  ('Bích Phương', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "bichnguyen.qnh", "followers": 0, "url": "https://www.tiktok.com/@bichnguyen.qnh"}]'::jsonb, 68),
  ('Việt Phương Nguyễn 🌼', NULL, ARRAY['Review', 'Lifestyle', 'Skincare', 'Makeup'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "phunreview", "followers": 0, "url": "https://www.tiktok.com/@phunreview"}]'::jsonb, 69),
  ('Nguyễn Ngọc', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nguyenngoc1xx5", "followers": 0, "url": "https://www.tiktok.com/@nguyenngoc1xx5"}]'::jsonb, 70),
  ('Linh Gấu', NULL, ARRAY['Parenting', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "linhgauvnn", "followers": 0, "url": "https://www.tiktok.com/@linhgauvnn"}]'::jsonb, 71),
  ('Nhung Rose', NULL, ARRAY['Review', 'Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nhungrose_1912", "followers": 0, "url": "https://www.tiktok.com/@nhungrose_1912"}]'::jsonb, 72),
  ('Đào Mỹ Lan', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mylanne03", "followers": 0, "url": "https://www.tiktok.com/@mylanne03"}]'::jsonb, 73),
  ('Hồng Hà Triệu', NULL, ARRAY['Livestream', 'Review', 'Parenting', 'Cosmetics'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "me_embun", "followers": 0, "url": "https://www.tiktok.com/@me_embun"}]'::jsonb, 74),
  ('MC Hồng Quốc', NULL, ARRAY['Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hongquoc58", "followers": 0, "url": "https://www.tiktok.com/@hongquoc58"}]'::jsonb, 75),
  ('Mẹ thỏ rùa review', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "methorua_review", "followers": 0, "url": "https://www.tiktok.com/@methorua_review"}]'::jsonb, 76),
  ('Hạnh Moe', NULL, ARRAY['Lifestyle', 'Review', 'Fashion', 'Travel'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hanh_moe", "followers": 0, "url": "https://www.tiktok.com/@hanh_moe"}]'::jsonb, 77),
  ('Cherry Review', NULL, ARRAY['Review', 'Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "cherryreview66", "followers": 0, "url": "https://www.tiktok.com/@cherryreview66"}]'::jsonb, 78),
  ('HàMyy🐰', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hamyyng", "followers": 0, "url": "https://www.tiktok.com/@hamyyng"}]'::jsonb, 79),
  ('Cami', NULL, ARRAY['Lifestyle', 'Personal Experiences', 'Skincare', 'Couple'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dieplinhcami", "followers": 0, "url": "https://www.tiktok.com/@dieplinhcami"}]'::jsonb, 80),
  ('Bơ Nguyễn', NULL, ARRAY['Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "bonguyenbo0", "followers": 0, "url": "https://www.tiktok.com/@bonguyenbo0"}]'::jsonb, 81),
  ('mehanaxinh', NULL, ARRAY['Family', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mehanaxinh", "followers": 0, "url": "https://www.tiktok.com/@mehanaxinh"}]'::jsonb, 82),
  ('Ceci', NULL, ARRAY['Vlog', 'Skincare', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "phuongganh", "followers": 0, "url": "https://www.tiktok.com/@phuongganh"}]'::jsonb, 83),
  ('Thanh Mi', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "rie.mii", "followers": 0, "url": "https://www.tiktok.com/@rie.mii"}]'::jsonb, 84),
  ('Nhà Hiếu Review', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mocmoc898", "followers": 0, "url": "https://www.tiktok.com/@mocmoc898"}]'::jsonb, 85),
  ('Nguyễn Loan', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nguyenloan.nkpd", "followers": 0, "url": "https://www.tiktok.com/@nguyenloan.nkpd"}]'::jsonb, 86),
  ('Emily Pham', NULL, ARRAY['Vlog', 'Skincare', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "emipnlu", "followers": 0, "url": "https://www.tiktok.com/@emipnlu"}]'::jsonb, 87),
  ('Thu Quỳnh Nguyễn', NULL, ARRAY['Review', 'Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "meimei8866", "followers": 0, "url": "https://www.tiktok.com/@meimei8866"}]'::jsonb, 88),
  ('Tâm Đan', NULL, ARRAY['Skincare', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "amelinda.dan__", "followers": 0, "url": "https://www.tiktok.com/@amelinda.dan__"}]'::jsonb, 89),
  ('Bùi Mỹ Anh', NULL, ARRAY['Review', 'Lifestyle', 'Cosmetics'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "myanhh0212", "followers": 0, "url": "https://www.tiktok.com/@myanhh0212"}]'::jsonb, 90),
  ('Ở đây có Hân và Lộc', NULL, ARRAY['Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nhahanngx", "followers": 0, "url": "https://www.tiktok.com/@nhahanngx"}]'::jsonb, 91),
  ('Thỏ Mymy', NULL, ARRAY['Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "snowbabyyx", "followers": 0, "url": "https://www.tiktok.com/@snowbabyyx"}]'::jsonb, 92),
  ('July mỹ', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "julymy11", "followers": 0, "url": "https://www.tiktok.com/@julymy11"}]'::jsonb, 93),
  ('Ngọc Bích', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "bichngoc_16", "followers": 0, "url": "https://www.tiktok.com/@bichngoc_16"}]'::jsonb, 94),
  ('Hạnh Nguyễn Hồng', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nghonghanh41", "followers": 0, "url": "https://www.tiktok.com/@nghonghanh41"}]'::jsonb, 95),
  ('Diệu Anh', NULL, ARRAY['Daily life'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dieuanhneeee", "followers": 0, "url": "https://www.tiktok.com/@dieuanhneeee"}]'::jsonb, 96),
  ('Huaquynhnhu', NULL, ARRAY['Lifestyle', 'Review', 'Makeup', 'Skincare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "_huaquynhnhu", "followers": 0, "url": "https://www.tiktok.com/@_huaquynhnhu"}]'::jsonb, 97),
  ('MC Khánh An', NULL, ARRAY['Lifestyle', 'Travel', 'Cosmetics'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "an.chunn", "followers": 0, "url": "https://www.tiktok.com/@an.chunn"}]'::jsonb, 98),
  ('Thạch Trang', NULL, ARRAY['Vlog', 'Review', 'Skincare', 'Fashion', 'Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "thach_trangg", "followers": 0, "url": "https://www.tiktok.com/@thach_trangg"}]'::jsonb, 99),
  ('Gia đình Hanna', NULL, ARRAY['Family', 'Review', 'Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "giadinhhanna", "followers": 0, "url": "https://www.tiktok.com/@giadinhhanna"}]'::jsonb, 100),
  ('Ngọc Ruby', NULL, ARRAY['Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "ngocruby89hn", "followers": 0, "url": "https://www.tiktok.com/@ngocruby89hn"}]'::jsonb, 101),
  ('Hàn Hằng', NULL, ARRAY['Cosmetics', 'Vlog'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "han.hang18", "followers": 0, "url": "https://www.tiktok.com/@han.hang18"}]'::jsonb, 102),
  ('Chây Xì Dách', NULL, ARRAY['Review', 'Vlog', 'Skincare', 'Makeup'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "chayxidach", "followers": 0, "url": "https://www.tiktok.com/@chayxidach"}]'::jsonb, 103),
  ('Nhỏ Ngọccc', NULL, ARRAY['Lifestyle', 'Travel', 'Beauty', 'Coffee Holic', 'F&B'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "nhongoccc95", "followers": 0, "url": "https://www.tiktok.com/@nhongoccc95"}]'::jsonb, 104),
  ('Trinh Meow', NULL, ARRAY['Livestream', 'Cosmetics', 'Skincare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "trinhmeow.vlogger", "followers": 0, "url": "https://www.tiktok.com/@trinhmeow.vlogger"}]'::jsonb, 105),
  ('Lyxinhnhat', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "lyxinhnhat", "followers": 0, "url": "https://www.tiktok.com/@lyxinhnhat"}]'::jsonb, 106),
  ('Yên Đan', NULL, ARRAY['Livestream', 'Lifestyle', 'Fashion', 'Skincare'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "yendan7", "followers": 0, "url": "https://www.tiktok.com/@yendan7"}]'::jsonb, 107),
  ('ABG Tina', NULL, ARRAY['Vlog', 'Personal Experiences', 'Makeup'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "abgtinaofficial", "followers": 0, "url": "https://www.tiktok.com/@abgtinaofficial"}]'::jsonb, 108),
  ('Bui Kha Han', NULL, ARRAY['Vlog', 'Travel', 'Skincare', 'Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "khahanbuii", "followers": 0, "url": "https://www.tiktok.com/@khahanbuii"}]'::jsonb, 109),
  ('Emly vn', NULL, ARRAY['Review', 'Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "emlyreview", "followers": 0, "url": "https://www.tiktok.com/@emlyreview"}]'::jsonb, 110),
  ('David Vink', NULL, ARRAY['Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "davidvink", "followers": 0, "url": "https://www.tiktok.com/@davidvink"}]'::jsonb, 111),
  ('Chu Minh Phúc', NULL, ARRAY['Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "chuminhphuc20111999", "followers": 0, "url": "https://www.tiktok.com/@chuminhphuc20111999"}]'::jsonb, 112),
  ('Trương Mỹ Nhân', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hana.mynhan", "followers": 0, "url": "https://www.tiktok.com/@hana.mynhan"}]'::jsonb, 113),
  ('Diệp Tít', NULL, ARRAY['Review', 'Parenting'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "dndiep1603", "followers": 0, "url": "https://www.tiktok.com/@dndiep1603"}]'::jsonb, 114),
  ('☁wwebpage🌩', NULL, ARRAY['Lifestyle', 'Fashion', 'Business', 'Couple'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "wwebpage", "followers": 0, "url": "https://www.tiktok.com/@wwebpage"}]'::jsonb, 115),
  ('Lenka Ngo', NULL, ARRAY['Vlog', 'Personal Experiences'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "lenkangoo", "followers": 0, "url": "https://www.tiktok.com/@lenkangoo"}]'::jsonb, 116),
  ('Chanhealthy', NULL, ARRAY['Lifestyle', 'Fitness', 'Family'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "chanhealthy", "followers": 0, "url": "https://www.tiktok.com/@chanhealthy"}]'::jsonb, 117),
  ('Ngô Mai Phương', NULL, ARRAY['Lifestyle', 'Family', 'Review', 'Cosmetics'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "ngomaiphuongg", "followers": 0, "url": "https://www.tiktok.com/@ngomaiphuongg"}]'::jsonb, 118),
  ('Xoài Phạm', NULL, ARRAY['Livestream', 'Lifestyle', 'Review', 'Beauty'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "xoai.phm", "followers": 0, "url": "https://www.tiktok.com/@xoai.phm"}]'::jsonb, 119),
  ('Châu Bí Ngô', NULL, ARRAY['Vlog', 'Review', 'Personal Experiences'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "chaubingo", "followers": 0, "url": "https://www.tiktok.com/@chaubingo"}]'::jsonb, 120),
  ('Mivi Diễm Anh', NULL, ARRAY['Review', 'Lifestyle', 'Cosmetics'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "mividiemanh", "followers": 0, "url": "https://www.tiktok.com/@mividiemanh"}]'::jsonb, 121),
  ('Do Hoang Lan', NULL, ARRAY['Lifestyle'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "do.hoang.lan", "followers": 0, "url": "https://www.tiktok.com/@do.hoang.lan"}]'::jsonb, 122),
  ('Hannah Olala', NULL, ARRAY['Vlog', 'Lifestyle', 'Review'], ARRAY['Vietnamese'], '[{"platform": "TikTok", "handle": "hannaholala", "followers": 0, "url": "https://www.tiktok.com/@hannaholala"}]'::jsonb, 123);

-- SQL 문 실행 후 삽입된 레코드 확인
SELECT COUNT(*) as total_inserted FROM vietnam_influencers WHERE name IN (
  'nanavivuvu', 'Tamii 따미', 'gjiang.g', 'Dolri.nn', 'dtthao.anh'
);
