import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function NavMenu({ href, label, desc }: { href: string; label: string; desc: string }) {
  return (
    <Link href={href} className="group flex flex-col items-center justify-center min-w-[90px] px-3 py-1 rounded-xl hover:bg-blue-800/70 transition text-white font-semibold relative">
      <span className="text-base whitespace-nowrap">{label}</span>
      <span className="absolute left-1/2 -bottom-2 translate-x-[-50%] translate-y-full opacity-0 group-hover:opacity-100 bg-[#181830] text-blue-200 text-xs rounded px-2 py-1 shadow-lg pointer-events-none transition z-20 whitespace-nowrap">
        {desc}
      </span>
    </Link>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-50 min-h-screen">
        {/* 네비게이션바 */}
        <nav className="sticky top-0 z-30 w-full bg-[#10112a]/80 backdrop-blur border-b border-blue-900 shadow-2xl">
          <div className="max-w-7xl mx-auto flex items-center justify-between px-8 py-4">
            {/* 왼쪽: 선정링크 로고 */}
            <Link href="/" className="flex items-center">
              <Image
                src="/logo/sunjeong_link_logo.png"
                alt="선정링크 로고"
                width={240}
                height={80}
                priority
                className="h-14 w-auto object-contain"
              />
            </Link>
            {/* 오른쪽: 메뉴 */}
            <div className="flex items-center gap-6 text-[15px] font-medium text-white">
              <NavMenu href="/auth" label="로그인/회원가입" desc="서비스 이용을 위한 계정 생성/로그인" />
              <NavMenu href="/campaigns" label="캠페인 리스트" desc="진행 중인 모든 캠페인 한눈에 보기" />
              <NavMenu href="/campaigns/new" label="캠페인 생성" desc="브랜드/셀러용 신규 캠페인 등록" />
              <NavMenu href="/influencers" label="인플루언서 리스트" desc="인플루언서 한눈에 보기" />
              <NavMenu href="/chat" label="실시간 채팅" desc="브랜드-인플루언서 실시간 소통" />
              <NavMenu href="/profile" label="내 프로필 관리" desc="이름, 역할, 소개, 프로필 이미지 관리" />
              <NavMenu href="/dashboard" label="내 대시보드" desc="내 서비스 현황 한눈에 보기" />
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
